- name: Build the web image 
  docker_image:
    build:
      path: ./roles/web/files/
    name: my_nginx
    source: "build"

- name: Build the nginx_container container from the my_db image
  docker_container:
    name: nginx_container
    image: my_nginx
    networks:
      - name: network
    ports:
    - "80:80"